sudo: required

language: nodejs

services:
  - docker

before_install:
  - docker build -t sitespeedio/coach .
  - docker ps -a

script:
  - docker run sitespeedio/coach webcoach https://www.sitespeed.io -b firefox
  - docker run sitespeedio/coach webcoach https://www.sitespeed.io -b chrome
